data:
        batch_size: 32
        datajson: 'fake_data/datajson.json' # the datajson file storing details of each study and sequence
        datarootdir: 'fake_data/data' # root dir of where the data is stored
        vqvaename: 'FAKE_TOKENIZER' # name of the VQ-VAE
        percentage: 5
        nosplit: true

train:
        devices: [0]
        vismodelpath: 'ckpts/fullmodel107.pt' # path to pre-trained full model checkpoint (e.g., fullmodel107.pt)
        epochs: 50
        lr: 0.00001
        momentum: 0.0
        weight_decay: 0.0
        save_top_k: 5
        use_wandb: false
        wandb_project: 'prima'
        wandb_entity: null
        wandb_run_name: 'classification_dry_run_fakeadata'
        ckptsavedir: ckpts/
        nums: ['last']
        retpool: true
cset:
        savesite: '.'
        markdate: '2025-fake-data-heads'
        classnum: 4
        names: ['fake_class_0', 'fake_class_1', 'fake_class_2', 'fake_class_3']
        train_csv: 'fake_data/retrospective_classification/train_labels.csv' # csv with two columns: study_id,class_id
        val_csv: 'fake_data/retrospective_classification/val_labels.csv' # csv with two columns: study_id,class_id
        test_csv: 'fake_data/retrospective_classification/test_labels.csv' # csv with two columns: study_id,class_id
